// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use anyhow::Result;
use bigdecimal::{FromPrimitive, ToPrimitive};
use chrono::NaiveDateTime;
use juniper::{GraphQLInputObject, GraphQLObject};
use uuid::Uuid;

use crate::{context::GraphQLContext, schema::*, svc::UploadSvc, uuid::UUID};
use bigdecimal::BigDecimal;
use diesel::prelude::*;

#[derive(Queryable, Debug, Identifiable, Insertable, Selectable, AsChangeset)]
#[diesel(primary_key(uuid), table_name = uploads)]
pub struct Upload {
    pub uuid: UUID,
    pub message: Option<String>,
    pub data: Vec<u8>,
    pub public: bool,
    pub uploaded_at: Option<NaiveDateTime>,
}

#[juniper::graphql_object(context = GraphQLContext)]
impl Upload {
    pub fn uuid(&self) -> Result<String> {
        let uuid = Uuid::from_slice(self.uuid.0.as_bytes())
            .map_err(|e| anyhow::anyhow!("Invalid UUID: {}", e))?;
        Ok(uuid.to_string())
    }
    pub fn message(&self) -> Option<&str> {
        self.message.as_deref()
    }
    pub fn data(&self) -> String {
        base64::encode(&self.data)
    }
    pub fn uploaded_at(&self) -> Option<NaiveDateTime> {
        self.uploaded_at
    }
    pub fn public(&self) -> bool {
        self.public
    }
}

#[derive(GraphQLInputObject, Debug, Clone)]
pub struct UploadInput {
    pub message: Option<String>,
    pub data: String,
    pub public: bool,
}
impl From<UploadInput> for Upload {
    fn from(input: UploadInput) -> Self {
        Self {
            uuid: UUID::random(),
            message: input.message,
            data: base64::decode(input.data).unwrap_or_default(),
            public: input.public,
            uploaded_at: Some(chrono::Utc::now().naive_utc()),
        }
    }
}
