// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use bigdecimal::{FromPrimitive, ToPrimitive};
use chrono::NaiveDateTime;
use juniper::{GraphQLInputObject, GraphQLObject};
use uuid::Uuid;

use crate::{context::GraphQLContext, schema::*, svc::UploadSvc};
use bigdecimal::BigDecimal;
use diesel::prelude::*;

#[derive(Queryable, Debug, Identifiable, Insertable, Selectable, AsChangeset)]
#[diesel(primary_key(id), table_name = uploads)]
pub struct Upload {
    pub id: i32,
    pub message: Option<String>,
    pub data: Vec<u8>,
    pub uploaded_at: Option<NaiveDateTime>,
}

#[juniper::graphql_object(context = GraphQLContext)]
impl Upload {
    pub fn id(&self) -> i32 {
        self.id
    }
    pub fn message(&self) -> Option<&str> {
        self.message.as_deref()
    }
    pub fn data(&self) -> String {
        base64::encode(&self.data)
    }
    pub fn uploaded_at(&self) -> Option<NaiveDateTime> {
        self.uploaded_at
    }
}

#[derive(GraphQLInputObject, Debug, Clone)]
pub struct UploadInput {
    pub id: i32,
    pub message: Option<String>,
    pub data: String,
}
impl From<UploadInput> for Upload {
    fn from(input: UploadInput) -> Self {
        Self {
            id: input.id,
            message: input.message,
            data: base64::decode(input.data).unwrap_or_default(),
            uploaded_at: Some(chrono::Utc::now().naive_utc()),
        }
    }
}
