// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use std::str::FromStr;

use crate::svc::packed_to_png;
use anyhow::Result;
use bigdecimal::{FromPrimitive, ToPrimitive};
use chrono::NaiveDateTime;
use juniper::{GraphQLEnum, GraphQLInputObject, GraphQLObject};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::{context::GraphQLContext, schema::*, svc::UploadSvc, uuid::UUID};
use bigdecimal::BigDecimal;
use diesel::prelude::*;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, GraphQLEnum)]
pub enum DisplayFormat {
    #[serde(rename = "RGB_320x240")]
    #[graphql(name = "RGB_320x240")]
    RGB320x240,
    #[serde(rename = "Esp32")]
    #[graphql(name = "Esp32")]
    Esp32,
}
impl DisplayFormat {
    pub(crate) fn as_str(&self) -> &str {
        match self {
            DisplayFormat::RGB320x240 => "RGB_320x240",
            DisplayFormat::Esp32 => "Esp32",
        }
    }
}

impl FromStr for DisplayFormat {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "RGB_320x240" => Ok(DisplayFormat::RGB320x240),
            "Esp32" => Ok(DisplayFormat::Esp32),
            _ => Err(anyhow::anyhow!("Invalid display format: {}", s)),
        }
    }
}

impl ToString for DisplayFormat {
    fn to_string(&self) -> String {
        self.as_str().to_owned()
    }
}

#[derive(
    Queryable, Debug, Identifiable, Insertable, Selectable, AsChangeset, PartialEq, Eq, Clone, Hash,
)]
#[diesel(primary_key(uuid), table_name = uploads)]
pub struct Upload {
    pub uuid: UUID,
    pub message: Option<String>,
    pub data: Vec<u8>,
    pub public: bool,
    pub uploaded_at: Option<NaiveDateTime>,
    pub name: Option<String>,
    pub display: Option<String>,
}

#[juniper::graphql_object(context = GraphQLContext)]
impl Upload {
    pub fn uuid(&self) -> Result<String> {
        let uuid = Uuid::from_slice(self.uuid.0.as_bytes())
            .map_err(|e| anyhow::anyhow!("Invalid UUID: {}", e))?;
        Ok(uuid.to_string())
    }
    pub fn message(&self) -> Option<&str> {
        self.message.as_deref()
    }
    pub fn data(&self) -> String {
        base64::encode(&self.data)
    }
    pub fn uploaded_at(&self) -> Option<NaiveDateTime> {
        self.uploaded_at
    }
    pub fn name(&self) -> Option<&str> {
        self.name.as_deref()
    }

    pub fn public(&self) -> bool {
        self.public
    }

    pub fn display(&self) -> Option<&str> {
        self.display.as_deref()
    }

    pub async fn img_src(&self) -> String {
        if self.display.as_deref() == Some(DisplayFormat::RGB320x240.as_str()) {
            return format!("data:image/jpeg;base64,{}", base64::encode(&self.data));
        }
        let png_data = packed_to_png(self.data.clone()).await;
        format!("data:image/png;base64,{}", base64::encode(&png_data))
    }
}

#[derive(GraphQLInputObject, Debug, Clone)]
pub struct UploadInput {
    pub message: Option<String>,
    pub data: String,
    pub name: Option<String>,
    pub public: bool,
    pub display: DisplayFormat,
}

impl From<UploadInput> for Upload {
    fn from(input: UploadInput) -> Self {
        Self {
            uuid: UUID::random(),
            message: input.message,
            data: base64::decode(input.data).unwrap_or_default(),
            public: input.public,
            uploaded_at: Some(chrono::Utc::now().naive_utc()),
            name: input.name,
            display: Some(input.display.to_string()),
        }
    }
}
